export const ghanaRegions = [
  ////////////////////////////// Greater Accra /////////////////////////////////
  {
    region: "Greater Accra",
    towns: [
      "Abeka",
      "Ablenkpe",
      "Abossey Okai",
      "Accra",
      "Achimota",
      "Adenta",
      "Adenta East",
      "Adjei Kojo",
      "Afienya",
      "Agbogbloshie",
      "Airport Residential Area",
      "Amasaman",
      "Ashaiman",
      "Awoshie",
      "Borteyman",
      "Cantonments",
      "Dansoman",
      "Dawhenya",
      "Dodowa",
      "Dome",
      "Dzorwulu",
      "East Legon",
      "Gbawe",
      "Kokomlemle",
      "Kokrobite",
      "Korle Gonno",
      "Kuntunse",
      "Labadi",
      "Labone",
      "Laterbiokorshie",
      "Lashibi",
      "Legon",
      "Maamobi",
      "Madina",
      "Mallam",
      "Mataheko",
      "Miotso",
      "Nima",
      "Nmai Dzorn",
      "North Industrial Area",
      "Nungua",
      "Ogbodjo",
      "Old Ningo",
      "Osu",
      "Oyarifa",
      "Pokuase",
      "Prampram",
      "Sabon Zongo",
      "Sakumono",
      "Santeo",
      "Sege",
      "Shiashie",
      "Sowutoum",
      "Sugbaniate",
      "Tema",
      "Tema Manhean",
      "Tesano",
      "Teshie",
      "Tetegu",
      "Torkuase",
      "Tse-Addo",
      "Tudu",
      "Weija",
    ],
  },

  /////////////////////// Ashanti Region ///////////////////////////////////
  {
    region: "Ashanti Region",
    towns: [
      "Aboaso",
      "Abodom",
      "Abono",
      "Adansi Asokwa",
      "Adum",
      "Agogo",
      "Agyemfra",
      "Ahwiaa",
      "Akrofuom",
      "Amakom",
      "Antoa",
      "Asamang",
      "Asante Mampong",
      "Asawasi",
      "Atonsu",
      "Bekwai",
      "Berekum",
      "Boadi",
      "Bonwire",
      "Ejisu",
      "Juaben",
      "Kumasi",
      "Kwadaso",
      "Mampongten",
      "Nkawie",
      "Nkenkaasu",
      "Nsuta",
      "Obuasi",
      "Offinso",
      "Oforikrom",
      "Old Tafo",
      "Santasi",
      "Suame",
      "Techiman",
      "Tepa",
      "Tewobaabi",
      "Trede",
      "Wiamoase",
    ],
  },

  /////////////////////// Eastern Region ///////////////////////////////////
  {
    region: "Eastern Region",
    towns: [
      "Aburi",
      "Adukrom",
      "Akosombo",
      "Akwapim-Mampong",
      "Amankwakrom",
      "Anum",
      "Asamankese",
      "Asuboi",
      "Bawjiase",
      "Begoro",
      "Boti Falls",
      "Bunso",
      "Damete",
      "Denu",
      "Donkorkrom",
      "Enyiresi",
      "Kade",
      "Kibi",
      "Koforidua",
      "Kwahu-Tafo",
      "Kyebi",
      "Mpraeso",
      "Nkawkaw",
      "Nsawam",
      "Obo",
      "Odumase Krobo",
      "Oduom",
      "Osino",
      "Peduase",
      "Suhum",
    ],
  },

  /////////////////////// Western Region ///////////////////////////////////

  {
    region: "Western Region",
    towns: [
      "Adubrim",
      "Adum Banso",
      "Agona",
      "Akotom",
      "Akwidaa",
      "Apremodo",
      "Asankragua",
      "Asempanaye",
      "Ateiku",
      "Awaso",
      "Axim",
      "Bawdie",
      "Bibiani",
      "Bogoso",
      "Bonsa",
      "Butre",
      "Daboase",
      "Dentokrom",
      "Diabene",
      "Dixcove",
      "Domun",
      "Ejan",
      "Elubo",
      "Enchi",
      "Essiama",
      "Half-Assini",
      "Juaboso",
      "Kengen",
      "Kojokrom",
      "Mpohor",
      "New Takoradi",
      "Nkroful",
      "Omanpe",
      "Prestea",
      "Samreboi",
      "Sefwi Wiawso",
      "Sekondi",
      "Shama",
      "Takoradi",
      "Tarkwa",
      "Tarkwa Nsuaem",
      "Wassa Akropong",
    ],
  },

  /////////////////////// Central Region ///////////////////////////////////

  {
    region: "Central Region",
    towns: [
      "Abakrampa",
      "Abandze",
      "Abura-Dunkwa",
      "Agona Asafo",
      "Ajumako",
      "Anomabu",
      "Apam",
      "Assin Fosu",
      "Assin Manso",
      "Awutu Breku",
      "Awutu Senya",
      "Biriwa",
      "Breman Asikuma",
      "Budumburam",
      "Cape Coast",
      "Dunkwa-on-Offin",
      "Efutu",
      "Ekumfi Ekrawfo",
      "Ekumfi Otuam",
      "Elmina",
      "Enyan Denkyira",
      "Esakyir",
      "Gomoa Fetteh",
      "Gomoa Manso",
      "Gomoa Tarkwa",
      "Hemang",
      "Kasoa",
      "Komenda",
      "Kormantse",
      "Mankessim",
      "Moree",
      "Mouri",
      "Mumford",
      "Nyanyano",
      "Nsaba",
      "Pomadze",
      "Saltpond",
      "Senya Beraku",
      "Swedru",
      "Twifo Praso",
      "Winneba",
      "Yamoransa",
    ],
  },

  /////////////////////// Volta Region ///////////////////////////////////

  {
    region: "Volta Region",
    towns: [
      "Abor",
      "Adaklu Waya",
      "Adidome",
      "Aflao",
      "Agbozume",
      "Agortime-Kpetoe",
      "Akatsi",
      "Amedzofe",
      "Anfoega",
      "Anyirawase",
      "Ave-Dakpa",
      "Battor",
      "Dabala",
      "Denu",
      "Dzodze",
      "Fume",
      "Have",
      "Ho",
      "Hohoe",
      "Juapong",
      "Kadjebi",
      "Keta",
      "Klikor",
      "Kpando",
      "Kpasa",
      "Kpedze",
      "Kpeve",
      "Kpoeta",
      "Logba Alakpeti",
      "Mepe",
      "Nyive",
      "Peki",
      "Sogakope",
      "Sokode",
      "Tefle",
      "Tegbi",
      "Todome",
      "Tsito",
      "Tsiame",
      "Ve Golokwati",
    ],
  },

  /////////////////////// Northern Region ///////////////////////////////////

  {
    region: "Northern Region",
    towns: [
      "Bimbagu",
      "Bimbilla",
      "Binde",
      "Bole",
      "Buipe",
      "Bunkpurugu",
      "Chereponi",
      "Daboya",
      "Damongo",
      "Datoyili",
      "Gushegu",
      "Gushiegu",
      "Janga",
      "Karaga",
      "Kpalbe",
      "Kpandai",
      "Kpandae",
      "Kpatinga",
      "Kpasenkpe",
      "Kumbungu",
      "Larabanga",
      "Lingbinsi",
      "Mion",
      "Nakpanduri",
      "Nanton",
      "Nyankpala",
      "Saboba",
      "Salaga",
      "Sang",
      "Savelugu",
      "Sawla",
      "Tamale",
      "Tatali",
      "Tolon",
      "Walewale",
      "Wulensi",
      "Yabum",
      "Yapei",
      "Yendi",
      "Zabzugu",
    ],
  },

  /////////////////////// Upper East Region ///////////////////////////////////

  {
    region: "Upper East Region",
    towns: [
      "Balungu",
      "Bawku",
      "Binaba",
      "Binde",
      "Bolgatanga",
      "Bongo",
      "Bongo Soe",
      "Chiana",
      "Fumbisi",
      "Garu",
      "Gowrie",
      "Gowrie-Kunkua",
      "Kandiga",
      "Kassena-Nankana",
      "Katiu",
      "Kologo",
      "Kpalwega",
      "Kugri",
      "Kulungugu",
      "Nangodi",
      "Navrongo",
      "Paga",
      "Paga Central",
      "Pusu-Namongo",
      "Pusiga",
      "Sakote",
      "Sandema",
      "Sirigu",
      "Tempane",
      "Teshie",
      "Tongo",
      "Vea",
      "Widana",
      "Wiaga",
      "Yikene",
      "Zebilla",
      "Zebilla Central",
      "Zorko",
      "Zuarungu",
    ],
  },

  /////////////////////// Upper West Region ///////////////////////////////////

  {
    region: "Upper West Region",
    towns: [
      "Babile",
      "Busa",
      "Charia",
      "Dabo",
      "Daffiama",
      "Dakpa",
      "Dorimon",
      "Duori",
      "Eremon",
      "Fian",
      "Funsi",
      "Gbare",
      "Goli",
      "Gwollu",
      "Hamile",
      "Jeffisi",
      "Jirapa",
      "Kaleo",
      "Kambali",
      "Kojokperi",
      "Koro",
      "Kparigu",
      "Lambussie",
      "Lawra",
      "Loggu",
      "Nadowli",
      "Nandom",
      "Naro",
      "Nyoli",
      "Piina",
      "Sabuli",
      "Sankana",
      "Takpo",
      "Tarsaw",
      "Tizza",
      "Tumu",
      "Ullo",
      "Wa",
      "Wechiau",
      "Zini",
    ],
  },

  /////////////////////// Bono Region //////////////////////////

  {
    region: "Bono Region",
    towns: [
      "Abease",
      "Adiembra",
      "Asunsu",
      "Badu",
      "Banda Ahenkro",
      "Bechem",
      "Berekum",
      "Bomini",
      "Chiraa",
      "Dormaa Ahenkro",
      "Dormaa Akwamu",
      "Drobo",
      "Dumasua",
      "Dwenem",
      "Fiapre",
      "Japekrom",
      "Kasuwa",
      "Kato",
      "Kokuma",
      "Kunkua",
      "Kwatire",
      "Kwasibuokrom",
      "Kwasikrom",
      "Kwasu",
      "Kyeremasu",
      "Nkrankwanta",
      "Nkoranza",
      "Nsoatre",
      "Nsuatre",
      "Odumase",
      "Sampa",
      "Seikwa",
      "Subinso",
      "Sunyani",
      "Techiman",
      "Wamfie",
      "Wenchi",
      "Yawhima",
    ],
  },

  /////////////////////// Bono East Region //////////////////////////

  {
    region: "Bono East Region",
    towns: [
      "Abease",
      "Akropong",
      "Akumsa Odumase",
      "Amoma",
      "Anyima",
      "Apesika",
      "Apesokubi",
      "Atebubu",
      "Babatokuma",
      "Badu",
      "Banda",
      "Bassa",
      "Bomini",
      "Buoyem",
      "Chache",
      "Forikrom",
      "Gulumpe",
      "Jama",
      "Jema",
      "Kadelso",
      "Kajeji",
      "Kintampo",
      "Krabonso",
      "Kranka",
      "Kwame Danso",
      "Makango",
      "Mo",
      "Nante",
      "New Longoro",
      "Nkoranza",
      "Nsuta",
      "Prang",
      "Senya",
      "Tanoso",
      "Techiman",
      "Tuobodom",
      "Wurishie",
      "Yabraso",
      "Yeji",
      "Zabrama",
    ],
  },

  /////////////////////// Ahafo Region //////////////////////////

  {
    region: "Ahafo Region",
    towns: [
      "Acherensua",
      "Adaboe",
      "Adabokrom",
      "Adrobaa",
      "Adupri",
      "Afrancho",
      "Afrisipa",
      "Ahyiresu",
      "Akrodie",
      "Asuogya",
      "Asutifi",
      "Ata ne Ata",
      "Bechem",
      "Dadieso",
      "Derma",
      "Duayaw-Nkwanta",
      "Goaso",
      "Gyedu",
      "Hwidiem",
      "Kenyasi",
      "Kokofu",
      "Kukuom",
      "Kwapong",
      "Kyeremasu",
      "Kyereyase",
      "Manhyia",
      "Mim",
      "Mpasaso",
      "Nkasiem",
      "Nkrankrom",
      "Nkwanta",
      "Nkwawie",
      "Ntotroso",
      "Odumase",
      "Sankore",
      "Subriso",
      "Susuanso",
      "Terchire",
      "Wamahinso",
      "Yamfo",
    ],
  },

  /////////////////////// Oti Region //////////////////////////

  {
    region: "Oti Region",
    towns: [
      "Ahamansu",
      "Apesokubi",
      "Atonkor",
      "Banda",
      "Banda Nkwanta",
      "Biakoye",
      "Bodada",
      "Borae",
      "Brewaniase",
      "Chaiso",
      "Chindiri",
      "Dambai",
      "Dodo Pepesu",
      "Jasikan",
      "Kadjebi",
      "Kadjebi Asato",
      "Kadjebi Central",
      "Kete Krachi",
      "Kete Krachi East",
      "Kete Krachi West",
      "Kpandai",
      "Kpassa",
      "Kpele",
      "Krachi Akura",
      "Krachi East",
      "Krachi Nchumuru",
      "Krachi Tepo",
      "Krachi West",
      "Kusuntu",
      "Kyeremade",
      "Nkwanta",
      "Nkwanta Central",
      "Nkwanta North",
      "Nkwanta South",
      "Pai",
      "Saboba",
      "Tutukpene",
      "Worawora",
    ],
  },

  /////////////////////// Savannah Region //////////////////////////

  {
    region: "Savannah Region",
    towns: [
      "Banda Nkwanta",
      "Bole",
      "Buipe",
      "Busunu",
      "Canteen",
      "Chache",
      "Daboya",
      "Damongo",
      "Fulfuso",
      "Gindabuo",
      "Jentilpe",
      "Kafaba",
      "Kalba",
      "Kiape",
      "Kigbape",
      "Kipo",
      "Kojokope",
      "Kpalbe",
      "Kpanshegu",
      "Kpansiya",
      "Kpembe",
      "Kusawgu",
      "Larabanga",
      "Lingbinsi",
      "Mankarigu",
      "Mpaha",
      "Murugu",
      "Ndewura Jakpa",
      "Ntereso",
      "Nyange",
      "Salaga",
      "Sawla",
      "Sonyo",
      "Tinga",
      "Tuna",
      "Yabum",
      "Yagaba",
      "Yapei",
      "Yipala",
      "Zongo",
    ],
  },

  /////////////////////// North East Region //////////////////////////

  {
    region: "North East Region",
    towns: [
      "Binde",
      "Bunkpurugu",
      "Chereponi",
      "Gambaga",
      "Gbambu",
      "Gbandaa",
      "Gbintiri",
      "Jang",
      "Janga",
      "Jiningsa",
      "Kpabia",
      "Kpalba",
      "Kpasenkpe",
      "Kpatia",
      "Kpatili",
      "Kpatinga",
      "Kpatua",
      "Kuldanali",
      "Kulikaraga",
      "Kulmasa",
      "Kulugungu",
      "Kunkua",
      "Langbensi",
      "Nakpachei",
      "Nakpanduri",
      "Nalerigu",
      "Namburugu",
      "Nasia",
      "Nayoku",
      "Sakogu",
      "Sambuli",
      "Sang",
      "Walewale",
      "Wulugu",
      "Wungu",
      "Yagaba",
      "Yunyoo",
      "Zabzugu",
      "Zagua",
      "Zangum",
    ],
  },

  /////////////////////// Western North Region  //////////////////////////

  {
    region: "Western North Region",
    towns: [
      "Adabokrom",
      "Adjoafua",
      "Akontombra",
      "Amoaya",
      "Anhwiaso",
      "Anyinabrim",
      "Asempanaye",
      "Asiri",
      "Asuopiri",
      "Awaso",
      "Ayiem",
      "Bekwai",
      "Bibiani",
      "Bodi",
      "Boinzan",
      "Bosomoiso",
      "Chirano",
      "Dadieso",
      "Debiso",
      "Enchi",
      "Essam-Debiso",
      "Juaboso",
      "Kofikrom",
      "Kokokrom",
      "Kwasikrom",
      "Mpataba",
      "Nkatieso",
      "Nsawora",
      "Nsuonsa",
      "Old Debiso",
      "Sefwi Asawinso",
      "Sefwi Bekwai",
      "Sefwi Bonwire",
      "Sefwi Datano",
      "Sefwi Dwenase",
      "Sefwi Paboase",
      "Sefwi Wiawso",
      "Suaman Dadieso",
      "Zongo",
    ],
  },
];
